# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-21 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('id2', '0016_auto_20171014_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='derniere_modif',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 8, 1, 16, 6220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='inscription',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 8, 1, 16, 6176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='id2/photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(default='', max_length=50, verbose_name='Prenoms'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('H', 'homme'), ('F', 'femme')], default='H', max_length=5),
        ),
        migrations.AlterField(
            model_name='pieceid',
            name='code',
            field=models.CharField(default=0, help_text="Pour autre,laisser '0'", max_length=60, unique=True, verbose_name='Numéro ou code de la pièce'),
        ),
        migrations.AlterField(
            model_name='pieceid',
            name='typePiece',
            field=models.CharField(choices=[('passeport', 'passeport'), ('cni', 'CNI'), ('recepisse', 'recepisse'), ('autre', 'autre carte')], max_length=15),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_serv',
            field=models.CharField(max_length=30, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='adresse',
            field=models.TextField(verbose_name='Adresse physique'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='description',
            field=models.TextField(verbose_name='Description sommaire'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='societe',
            name='nom',
            field=models.CharField(max_length=30, verbose_name='Nom structure'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='usager',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='prenom',
            field=models.CharField(default='', max_length=50, verbose_name='Prenoms'),
        ),
        migrations.AlterField(
            model_name='usager',
            name='sexe',
            field=models.CharField(choices=[('H', 'homme'), ('F', 'femme')], default='H', max_length=5),
        ),
        migrations.AlterField(
            model_name='visite',
            name='date_arrivee',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 8, 1, 16, 4844, tzinfo=utc), verbose_name='Heure Arrivée'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='date_deprt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure Depart'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='type_visit',
            field=models.TextField(default='AUF', verbose_name='Objet de la Visite'),
        ),
        migrations.AlterField(
            model_name='visiteprof',
            name='date_arrivee',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 8, 1, 16, 5411, tzinfo=utc), verbose_name='Heure Arrivée'),
        ),
        migrations.AlterField(
            model_name='visiteprof',
            name='date_deprt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure Depart'),
        ),
        migrations.AlterField(
            model_name='visiteprof',
            name='type_visit',
            field=models.TextField(default='Courrier', verbose_name='Objet de la Visite'),
        ),
    ]
