# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-21 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('id2', '0017_auto_20171021_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='derniere_modif',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 9, 26, 7, 317157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='inscription',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 9, 26, 7, 317114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visite',
            name='date_arrivee',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 9, 26, 7, 315774, tzinfo=utc), verbose_name='Heure Arrivée'),
        ),
        migrations.AlterField(
            model_name='visiteprof',
            name='date_arrivee',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 9, 26, 7, 316341, tzinfo=utc), verbose_name='Heure Arrivée'),
        ),
    ]
