# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('id2', '0018_auto_20171021_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='derniere_modif',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 12, 46, 1, 557217, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='inscription',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 12, 46, 1, 557174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visite',
            name='date_arrivee',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 12, 46, 1, 555819, tzinfo=utc), verbose_name='Heure Arrivée'),
        ),
        migrations.AlterField(
            model_name='visiteprof',
            name='date_arrivee',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 12, 46, 1, 556386, tzinfo=utc), verbose_name='Heure Arrivée'),
        ),
    ]
