# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('id2', '0021_auto_20171022_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='derniere_modif',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 16, 57, 15, 376264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='inscription',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 16, 57, 15, 376221, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visite',
            name='date_arrivee',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 16, 57, 15, 374841, tzinfo=utc), verbose_name='Heure Arrivée'),
        ),
        migrations.AlterField(
            model_name='visiteprof',
            name='date_arrivee',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 16, 57, 15, 375400, tzinfo=utc), verbose_name='Heure Arrivée'),
        ),
    ]
