# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('id2', '0022_auto_20171022_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonne',
            name='derniere_modif',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='abonne',
            name='inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visite',
            name='date_arrivee',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure Arrivée'),
        ),
        migrations.AlterField(
            model_name='visiteprof',
            name='date_arrivee',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure Arrivée'),
        ),
    ]
