# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-01 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id2', '0024_auto_20171101_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usager',
            name='piece',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='id2.PieceId'),
        ),
    ]
