# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('id2', '0025_auto_20171101_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='usager',
            name='d_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date inscription'),
        ),
    ]
