# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id2', '0026_usager_d_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usager',
            name='en_dessous',
            field=models.BooleanField(default=True, help_text='Moins de 35 ans?'),
        ),
    ]
