# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Mobilier,info,élec,...', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('valeur', models.PositiveIntegerField(blank=True)),
                ('section', models.CharField(choices=[('INF', 'COM-INF'), ('ARE', 'COM-ARE')], default='INF', max_length=10)),
                ('numero', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('identifiant', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Implantation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(default='Piece', max_length=200)),
                ('prix_achat', models.PositiveIntegerField(blank=True)),
                ('num_serie', models.CharField(blank=True, max_length=200, verbose_name='Numéro de série')),
                ('fonctionnel', models.BooleanField(default=True, help_text='Est-ce que ça marche?')),
                ('usage', models.CharField(choices=[('personnel', 'Personnel'), ('infrastructure', 'Infrastructure'), ('usager', 'Usager'), ('projet', 'Projet')], default='personnel', help_text='Personnel,usager ?', max_length=20)),
                ('date_acquisition', models.DateField()),
                ('code_inventaire', models.CharField(help_text='ex CG1 I9012', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('commentaire', models.TextField(blank=True)),
                ('sortie_inventaire', models.BooleanField(default=False, help_text="Sortie d'inventaire ?")),
                ('periode_amortissement', models.PositiveIntegerField(default=4, help_text="En nombre d'années")),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire2.Categorie')),
                ('commande_coda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire2.Commande')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire2.Devise')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('constructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire2.Marque')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire2.Implantation')),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom structure')),
                ('adresse', models.TextField(verbose_name='Adresse physique')),
                ('description', models.TextField(verbose_name='Description sommaire')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('site_web', models.URLField(blank=True)),
                ('id_CODA', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='emplacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire2.Salle'),
        ),
        migrations.AddField(
            model_name='piece',
            name='modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire2.Produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='devise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire2.Devise'),
        ),
        migrations.AddField(
            model_name='commande',
            name='livree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire2.Societe'),
        ),
        migrations.AlterUniqueTogether(
            name='commande',
            unique_together=set([('section', 'numero')]),
        ),
    ]
