# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ville',
        ),
    ]
