# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire2', '0002_delete_ville'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together=set([('modele', 'constructeur')]),
        ),
    ]
