# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire2', '0004_auto_20171022_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['constructeur', 'modele']},
        ),
        migrations.AlterModelOptions(
            name='salle',
            options={'ordering': ['site', 'nom']},
        ),
        migrations.AlterField(
            model_name='piece',
            name='prix_achat',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
