# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire2', '0005_auto_20171022_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='section',
            field=models.CharField(choices=[('INF', 'COM-INF'), ('ARE', 'COM-ARE'), ('AUTRE', 'Autre')], default='INF', help_text="Utilisez 'Autre' si vous ne connaissez pas                     la commande", max_length=10),
        ),
    ]
