# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('id2', '0023_auto_20171031_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=150)),
                ('intitule', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('periode', models.DateField()),
                ('duree', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manif.Evenement')),
                ('usager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='id2.Usager')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='participant',
            field=models.ManyToManyField(through='manif.Participation', to='id2.Usager'),
        ),
    ]
