# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manif', '0003_auto_20171101_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='periode',
            new_name='debut',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='duree',
        ),
        migrations.AddField(
            model_name='evenement',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
