# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-26 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manif', '0004_auto_20171103_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='id2.Service'),
        ),
    ]
